### ISSUE TITLE
There is an SSE instruction in pf_neon_float.h.

### ISSUE THREAD

**Issue by uctakeoff** [marton78/pffft#14]
```c
/* reverse/flip all floats */
#  define VREV_S(a)    _mm_shuffle_ps(a, a, _MM_SHUFFLE(0,1,2,3))
/* reverse/flip complex floats */
#  define VREV_C(a)    _mm_shuffle_ps(a, a, _MM_SHUFFLE(1,0,3,2))
```

Perhaps the following is correct.

```c
/* reverse/flip all floats */
#  define VREV_S(a)    vcombine_f32(vrev64_f32(vget_high_f32(a)), vrev64_f32(vget_low_f32(a)))
/* reverse/flip complex floats */
#  define VREV_C(a)    vextq_f32(a, a, 2)
```

I consulted the following site.

https://stackoverflow.com/questions/32536265/how-to-convert-mm-shuffle-ps-sse-intrinsic-to-neon-intrinsic

**Comment by hayguen** [comment]
don't know how QA could miss this compile error!?
however, performance measurement isn't necessary, as it was a compile error on ARM/NEON platform.
compilation and tests run fine with suggested solution on Raspberry Pi 4B.

**Comment by marton78** [comment]
Oh sorry, I misunderstood the issue at hand. I didn't see it's about SSE instructions in NEON code.
