### ISSUE TITLE
Prime decomposition

### ISSUE THREAD

**Issue by elfman2** [marton78/pffft#16]
It seems that this implementation does not support N decomposition with prime > 5 which was initialy supported by FFTPACK.
ifac variable in decompose output is incorrect and only contains primes <= 5. 
Ex: N=55
 FFTPACK legacy can decompose 55 as ifac {5,11}.
 PFFFT decompose reports ifac={5}
There is no return code nor assertion that reports this limitation, and the limitation is only documented in pffft.h file => u could add the limitation to README ?
Or  add bluestein support ?

**Comment by hayguen** [comment]
i'm not that expert .. to add more decompositions .. besides .. it's lots of work.
adding bluestein sounds very interesting ..
limitation and error code: i need to check that ..

(multiple issues should have been created for better tracability)
