### ISSUE TITLE
Support for unaligned arrays

### ISSUE THREAD

**Issue by dievsky** [marton78/pffft#22]
Do I get it right that the library only supports aligned arrays as input (and output)? Is there a way to make it work with a non-aligned array?

Background: I'm trying to wrap the library in Java Native Interface, but it keeps crashing with a segfault at a `vmovapd` instruction. Inspecting the register dump, I can see that the library is indeed trying to aligned-load to an AVX register an address that's only aligned to 16 bytes. Java's double arrays are normally aligned to 32 bytes, but they also have a 16-byte header.

**Comment by marton78** [comment]
I believe this is a limitation of AVX. You could either add padding to the beggining of the array (two doubles or four floats) or disable AVX using the `DISABLE_SIMD_AVX` flag. Have a look at https://github.com/marton78/pffft/blob/master/CMakeLists.txt for all compile time parameters you could use.

**Comment by dievsky** [comment]
In my experience, SIMD methods usually have a scalar part dealing with potential unaligned prefix and/or suffix of the array. I don't know how feasible it is with `FFT`, but I would certainly like to avoid copying an entire array just to add padding.

**Comment by hayguen** [comment]
@dievsky : yes, you are right. there are intrinsics for aligned and also unaligned memory access - for SSE(2) and also AVX. for some parts (think convolution), the unaligned variants are even already used. with modern x64 CPUs, the unaligned access is told not to be slower .. as for older CPUs.
* what is your CPU?
* how important is performance (on older CPUs) for you?
* could you benchmark/measure before changing anything
* could you change VLOAD_ALIGNED() macros in the simd folder to have same content as the VLOAD_UNALIGNED() macros and benchmark again? does this run/work at all?

don't forget to send me/us both benchmark results ( see README of https://github.com/hayguen/pffft_benchmarks ) - ideally on Linux .. then we can decide, if we should add a 2nd unaligned FFT call

@marton78 `DISABLE_SIMD_AVX` does completely deactivate AVX .. but SSE(2) still requires some alignment ..

**Comment by hayguen** [comment]
please test following pull request https://github.com/marton78/pffft/pull/23
with the new cmake option `USE_UNALIGNED` (directly on my fork https://github.com/hayguen/pffft)

**Comment by marton78** [comment]
> `DISABLE_SIMD_AVX` does completely deactivate AVX .. but SSE(2) still requires some alignment ..

Of course, but as @dievsky wrote, the arrays in question are 16 byte aligned, which is just what SSE2 needs -- if my memory doesn't fail me.

In any case, thanks for the PR, @hayguen. Since the new flag is disabled by default, this is a non-breaking change, so I already merged it, but unfortunately before reading your comment. If @dievsky reports back any problems, I'll restore `master` and force push. Sorry.

**Comment by hayguen** [comment]
looks, i didn't read, that there's already some alignment.
however, calculating multiple FFTs from one time data vector is some odd sample distances might be a valid issue ..

**Comment by dievsky** [comment]
Thank you @hayguen and @marton78  for the quick reply! I think a bit more explanation is in order here.
Our library [viktor](https://github.com/JetBrains-Research/viktor/) is intended to bring SIMD capabilities to JVM. We support a range of OSes and architectures, and when we don't, there are fallback JVM implementations. Currently, we only work with `double` values. Since we also support arrays with offset, we have no guarantees on the array alignment beyond JVM's tendency to align to 8 bytes. Using unaligned loads / stores will probably be an acceptable solution.
I'll be sure to try the new version and report back the results.

**Comment by dievsky** [comment]
Unfortunately, the new option didn't seem to help. I won't pretend to understand everything that's going on in the library, but this is what I see:
- the pull request introduces a new cmake option, `USE_UNALIGNED`;
- this option, when enabled, defines the preprocessor symbol `PFFFT_UNALIGNED_ACCESS`;
- the symbol is used to re-define another symbol `VLOAD_ALIGNED`;
- that other symbol is used just once, in `FUNC_VALIDATE_SIMD_EX` which looks like a validation method.

The binary code generated by cmake for `pffftd_transform_internal` method still contains aligned-load instructions.

**Comment by hayguen** [comment]
I didn't test with unaligned memory. I'll have a deeper look ..

**Comment by hayguen** [comment]
@dievsky sorry, that's too much work todo. abandoned that. i suggest copying input/output vectors!
@marton78 yes, one of us should revert my previous patch

**Comment by marton78** [comment]
@hayguen done!

**Comment by dievsky** [comment]
Not yet. Should I be? From the docs, it looks like there are no multidimensional arrays, no fast exponentiation etc. (And no FFT too.)

**Comment by dievsky** [comment]
While we're here, maybe you could help me to understand how the library works in general? Let's say I want an FFT of a complex array. If I execute the following code:
```c
  std::complex<double> test_x[8], test_y[8];
  test_x[0] = 8.0;
  test_x[1] = 4.0;
  test_x[2] = 8.0;
  test_x[3] = 0.0;
  test_x[4] = 8.0;
  test_x[5] = 4.0;
  test_x[6] = 8.0;
  test_x[7] = 0.0;
  pffft::Fft<std::complex<double> > fft(8);
  fft.forward(test_x, test_y);
```
will `test_y` contain the FFT-transformed values?

**Comment by hayguen** [comment]
with 'std::complex<double> test_x[8], test_y[8];' you are creating the arrays on the stack - without guaranteed alignment.
that might crash!
besides that, you want a complex fft .. but are filling in only real values !?
last not least, pffft requires a minimum fft size. not sure now, if 8 is already big enough. probably you need minimum 16 values.

**Comment by dievsky** [comment]
1. I've replaced `std::complex test_x[8], test_y[8];` with `std::complex<double> * test_x = new std::complex<double>[16], * test_y = new std::complex<double>[16];`. (I know they're still not guaranteed to be aligned, but they usually are, and it's good enough for me for now.)
2. Real numbers are a special case of complex numbers, I see no error here. :))
3. This is probably the most important part. It's unfortunate that it doesn't seem to be mentioned or checked anywhere...

Taking your suggestions into account, I was able to get the expected result. Thanks!

**Comment by dievsky** [comment]
FYI: I think I've managed to add the support for unaligned arrays, see my fork https://github.com/dievsky/pffft . Redefining `v4sf` typedef seems to have done the trick.

**Comment by unevens** [comment]
hey guys, sorry i'm a bit late to the party. 
i agree with @dievsky about the lack of checks for the minimum fft size, so i prepared a little pull request that adds them.

**Comment by hayguen** [comment]
@dievsky  i picked your commit and tried on this branch: https://github.com/hayguen/pffft/tree/unaligned
but without success on linux :-(

**Comment by dievsky** [comment]
@hayguen to be honest, I haven't tested it on anything else than AVX and doubles. (This being the main pain point: we only have double arrays, and they're 16B-aligned, so SSE2 is not a problem,)
I can only say that my fork assembles successfully on my machine with `-DUSE_UNALIGNED=ON` and actually generates unaligned load / store binary instructions on AVX.

**Comment by unevens** [comment]
@dievsky @hayguen 
i also tried it on windows. i was able to build it using clang-CL, but not with MSVC. 
i think that `__m256d_u` is only available on clang. 
anyway, i tried to run some tests, in which i made the addresses unaligned by hand, but it crashed. 

the definition of `__m256d_u` that i see on my machine using clang-CL is 

    typedef double __m256d_u __attribute__((__vector_size__(32), __aligned__(1)));

from `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\Llvm\x64\lib\clang\11.0.0\include\avxintrin.h`

i don't think that using it should help with supporting unaligned arrays, but maybe on linux or macOS things are different.

**Comment by dievsky** [comment]
I thought that `__aligned__(1)` means "aligned to 1 byte", so effectively not aligned.

**Comment by unevens** [comment]
yeah, i think so too :) 
but i don't understand how it is supposed to help with calls to `_mm_load_pd`. 
what os/compiler are you using?

**Comment by dievsky** [comment]
@unevens oh, it's easy: as far as I'm able to tell, the only point preventing unaligned access in FFT is this snippet from `pffft_priv_impl.h`, method `FUNC_TRANSFORM_INTERNAL`:
```
// const double *finput, double *foutput
const v4sf *vinput = (const v4sf*)finput;
v4sf *voutput      = (v4sf*)foutput;
```
There are no calls to `_mm_load_pd` there, just dereferencing those pointers. If `v4sf` aliases an aligned vector, then dereferencing fails with SIGSEGV on unaligned pointers. If we change the typedef to the unaligned vector, the problem goes away.

I'm using Linux, `g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`.

**Comment by unevens** [comment]
@dievsky thank you for explaining, now that i understand i will look into it more and see if we can make it work also on other platforms, at least with clang.

**Comment by dievsky** [comment]
I had surprising results on other systems.
My macOS setup (clang 11) refuses to compile with unaligned definitions (e.g. it claims `__m256d_u` is not defined). However, with "aligned" definitions (like `__m256d`), it actually has no problems with loading unaligned arrays!
The Windows build (Visual Studio 14 2015), on the other hand, fails to compile completely, producing dozens of syntax errors.

**Comment by unevens** [comment]
`__m256d_u` is also not defined visual studio 2019. but it is defined with the llvm backend for visual studio (see https://docs.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-160). i tested your branch with it, and it builds ok, and it passes the tests (with some tweaks in the cmake file to set the PFFFT_UNALIGNED_ACCESS macro also on the test executables). 
but in the tests, the input array are aligned. if i manually make them unaligned, it crashes.

a possible solution (without using `__m256d_u`) could be to change things like

    const v4sf *vinput = (const v4sf*)finput;

to something like

    #ifdef PFFFT_UNALIGNED_ACCESS 
        const v4sf vinput_ = VLOAD_UNALIGNED(finput);
        const v4sf *vinput = &vinput_;
    #else
        const v4sf *vinput = (const v4sf*)finput;
    #endif

but i did not try it and i am not sure how much work would be needed to do that.

there are also some assertion that would need to be disabled when PFFFT_UNALIGNED_ACCESS  is defined.
