### ISSUE TITLE
Missing September 2016 commit

### ISSUE THREAD

**Issue by Lewiscowles1986** [marton78/pffft#39]
So something really weird is going on... First, thanks for hosting a mirror of sorts.

A Software called VCVRack requires pffft library.
I've got a github action which builds that software from source for a few versions across all three major OS's.
It's run successfully in 2020 fetching a https://bitbucket.org/jpommier/pffft/get/29e4f76ac53b.zip which does not seem to exist any more. The files in that archive are from September 22 2016, which is not a commit I can see on bitbucket or here.

Why does it seem like the original author and this repo have missing commits?

**Comment by Lewiscowles1986** [comment]
Here is a copy of the archive from a mirror (luckily vendor dependencies.)
[29e4f76ac53b.zip](https://github.com/marton78/pffft/files/6595951/29e4f76ac53b.zip)

**Comment by hayguen** [comment]
this repo was forked long time ago .. and we have several additions; amongst:
* improved benchmarking
* double support
* avx(2) support
* c++ headers
* additional API functions
* additional library for fast convolution
* cmake support
* ctest
* probably more

you're right, the documentation requires an update to explain this.

just seeing, that Julien did recent updates in May 2021 on https://bitbucket.org/jpommier/pffft/src/master/
we need to check the changes .. and merge into this repo ..

**Comment by Lewiscowles1986** [comment]
Hey, this wasn't my point, but I am so glad you realized this.

My point was that a specific commit was totally missing from the commit log, and it's from September 2016!

**Comment by hayguen** [comment]
from September 2016, i found the commit
"added support for 64-bit arm (the preprocessor tests had to be fixed) + benchmark on ipad air 2"
in https://bitbucket.org/jpommier/pffft/commits/74d7261be17cf659d5930d4830609406bd7553e3

this commit has been merged into this fork in December 2019. see here:
https://github.com/marton78/pffft/commit/3673ac0e55d486c244d1feb636fcea8aeed57088


there were very recent updates of Gregor and Julien on bitbucket. i've created pull a request for both:
https://github.com/marton78/pffft/pull/43

other commits on bitbucket are just changes in README (format)

however, this fork is definitely NO drop in replacement for the version on bitbucket,
cause sources got restructured and now we have way **more** source files in this fork!
thus, VCVRack Makefiles **will need** changes. think, it would be best, if it linked against static pffft library.

**Comment by hayguen** [comment]
think this is resolved .. else reopen
