### ISSUE TITLE
apple support

### ISSUE THREAD

**Issue by unevens** [marton78/pffft#46]
i have an experimental branch with support for Apple M1 and Raspberry 400. 
it is here https://github.com/unevens/pffft/tree/m1
i'm not sure about the stuff that i commented regarding `"-mfpu=neon"`, which may need to be conditionally enabled on other platforms.

**Comment by marton78** [comment]
@hayguen wanna check it?

**Comment by emmenlau** [comment]
Sounds great! @unevens is your branch still working well for you? Problems so far?

**Comment by unevens** [comment]
I've not been using this in a while. if I remember correctly it was definitely building and passing the tests, but you might want to check if the SIMD instructions are actually been used, instead of the scalar fallbacks.

**Comment by hayguen** [comment]
@marton78 : just re-noticed this issue .. and saw your question: sorry, i didn't check anything.
i need to check/sort my branches with major changes in cmake and platform/optimization settings ... and finalize a push requests ..
afterwards we could check for apple support .. or if apple could be checked/run also with github actions.

**Comment by unevens** [comment]
looks good to me : )

**Comment by hayguen** [comment]
@unevens @emmenlau  : would/could you check Apple M1 and Raspberry Pi 400 again? - with my last changes in the cmake files

**Comment by emmenlau** [comment]
Awesome, yes!

**Comment by hayguen** [comment]
@emmenlau : what exact platform did you check?
i'm curious about the Apple M1 results ..  would you run the benchmark and send me the results?

**Comment by emmenlau** [comment]
I'm actually building for Android, but we do not have a good test platform yet. We're currently just getting ready for Android support, but we do not have Android test devices, especially none that can run the build system or standard tests.

**Comment by hayguen** [comment]
Ok, thanks anyway.
Probably, you can submit benchmarks later
