### ISSUE TITLE
Question about real forward transform output size

### ISSUE THREAD

**Issue by OnceJune** [marton78/pffft#54]
Hi, I tried to use pffft in my project and I found output size is different between pffft and fftw.
In a N sample real forward fft, the output of pffft is of length N, with re and im interleaved. While in a fftw, the output is a fftw_complex which holds N samples real and N samples image.
Could anyone tell the different?

**Comment by hayguen** [comment]
as written in https://www.fftw.org/fftw3_doc/Real_002ddata-DFT-Array-Format.html

> The output of a DFT of real data (r2c) contains symmetries that, in principle, make half of the outputs redundant


PFFFT does not save/output the redundant values, as described in the C++ interface:
https://github.com/marton78/pffft/blob/master/pffft.hpp#L241-L248


on the symmetry, have a look here https://en.wikipedia.org/wiki/Fast_Fourier_transform#FFT_algorithms_specialized_for_real_or_symmetric_data  or  https://dsp.stackexchange.com/questions/8715/symmetry-of-real-and-imaginary-parts-in-fft
