### ISSUE TITLE
Support for 2D?

### ISSUE THREAD

**Issue by emmenlau** [marton78/pffft#56]
Thanks for this great library! Is there a plan to support also 2D transforms? It would be quite helpful.

**Comment by hayguen** [comment]
sorry, there are no such plans.
but pull requests would be welcome ..

**Comment by emmenlau** [comment]
I see! That's very sad. We can possibly implement a 2D transform based on repeated application of the 1D transform, but I guess that will not give the best possible performance (?) Do you know instructions how to implement the 2D transform efficiently?

**Comment by hayguen** [comment]
sorry, i have absolutely no clue: never used 2D FFT and never thought about it's implementation.
i need/use FFT only for signal/audio processing - not on images.
and i fear @marton78  also has knowledge on 2D FFTs

**Comment by marton78** [comment]
That is correct unfortunately, I've never used 2D FFT, I'm sorry.

**Comment by emmenlau** [comment]
Ok, thanks a lot for the quick feedback. I'll try and see what we can do, but implementing an efficient 2D transform may not be so easy.
