### ISSUE TITLE
Comparison with KissFFT

### ISSUE THREAD

**Issue by JulienMaille** [marton78/pffft#57]
Hello, I just discovered this library thanks to GitHub Explore feature.
It reminds me of https://github.com/mborgerding/kissfft which was developed with the same approach. Simple code and good performance. Have you ever tried it and compared some benchmarks?

**Comment by hayguen** [comment]
meanwhile, the code of pffft isn't that simple anymore. but optimizations and additional functions (fast convolution and more tests) have it's price on code size.

for comparison have a look at
https://github.com/hayguen/pffft_benchmarks/blob/master/i7-8550U_gcc-9.3.0_x64_Ubuntu-20.04.1LTS.md
or
https://github.com/hayguen/pffft_benchmarks
in general. not all test results may contain kissfft .. and if available, it's likely not to be the latest revision of kiss.

but you could run the benchmarks on your computer(s) and send me the results.
