### ISSUE TITLE
double precision support with avx instructions

### ISSUE THREAD

**Issue by unevens** [marton78/pffft#6]
I've a [fork of this library](https://github.com/unevens/pffft) in which I added support for double precision floating point numbers using AVX instructions.
I'd be happy to send you a pull request if you are interested.

**Comment by hayguen** [comment]
in general, that sounds interesting.
i'm unsure for AVX, which limits it's usage .. we would need some runtime switching ..

**Comment by unevens** [comment]
Nice to hear that!

Regarding your concerns: 

I implemented the double precision version of PFFFT in the files [pffft-double.h](https://github.com/unevens/pffft/blob/master/pffft-double.h) and [pffft-double.c](https://github.com/unevens/pffft/blob/master/pffft-double.c), because the double precision api needs different function signatures from the single precision one.

When AVX instructions are not supported the code in `pffft-double.c` will fall back to scalar operations, as PFFFT already does if no SIMD instruction is set available.

Also, the file `pffft.hpp` implements a c++ template class that abstract over the 32 bit PFFFT and the 64 bit PFFFT.

**Comment by hayguen** [comment]
had a quick look at your sources, which look quite good.

i would suggest to have multiple patches, e.g.:
1. OOURA FFT in a git submodule with cmake option, that it's optional - similar to greenffts and kissfft
2. core C implementation
3. C++ wrapper

however, just a suggestion.

what i noticed: you added normalization to your Inverse() method in the C++ wrapper. i'd recommend to have this optional, that the multiplication is only applied when required


later on we'd need to:
* extract the SIMD headers for the different architectures: SSE1, AVX, Altivec, NEON and SCALAR for each of float / double - leaving some unimplemented
* we need some runtime switching, which CPU features are available .. and also depending on (minimum) FFT length. had this thinking also on SSE1 .. but up to SSE2 is guaranteed on intel x64, that it had no hurry ..

**Comment by unevens** [comment]
Thanks.

You make good points. I'll prepare the patches and make the normalization optional.

I don't think that I undestand what you mean by runtime switching. In all the usage scenario I have in mind the instruction set is chosen at compile time by the preprocessor macros in the .c files, while the template abstracts over double/float.

**Comment by hayguen** [comment]
what i think of is to determine available cpu features like SSE1, SSE2, AVX, AVX512, .. (use some lib for this) and store best usable function pointer(s) in the PFFFT_Setup struct at initialization in pffft_new_setup().

however, don't mind for now. i'll implement when having enough time.
