### ISSUE TITLE
confusion about memory alignment.

### ISSUE THREAD

**Issue by qiny1012** [marton78/pffft#66]
Hello, I have some questions about this part of the code related to memory alignment. 
```c
static void * Valigned_malloc(size_t nb_bytes) {
  void *p, *p0 = malloc(nb_bytes + MALLOC_V4SF_ALIGNMENT);
  if (!p0) return (void *) 0;
  p = (void *) (((size_t) p0 + MALLOC_V4SF_ALIGNMENT) & (~((size_t) (MALLOC_V4SF_ALIGNMENT-1))));
  *((void **) p - 1) = p0;
  return p;
}
``` 
When p0 is allocated an address of xxxxx63, the aligned address after alignment would be xxxxx64, and *((void **) p - 1) would exceed the space of p0.
This is my understanding, is it correct?

**Comment by unevens** [comment]
p-1 would be xxxxx63, which is the "start" of the space of p0.
This algorithm always leave some space before p, 1 in the case you mentioned, and up to the whole MALLOC_V4SF_ALIGNMENT if p0 is already aligned.
In this way, one can safely assume to access p-1 and retrieve the value of p0 to free the memory later on.
